### ISSUE TITLE
yarn2nix should print errors on stderr

### ISSUE THREAD

**Issue by flokli** [Profpatsch/yarn2nix#13]
When running yarn2nix from a checkout not containing a yarn.lock file, the error message about it not being there gets printed to stdout instead of stderr (together with usage information).

As the README suggests to pipe the output into `npm-deps.nix`, one does not immediatly see this (except from the return code), so this might fail at a later stage, as soon as nix tries to parse the `npm-deps.nix` file.

**Comment by Profpatsch** [comment]
Good catch! I’ll fix this today.

**Comment by Profpatsch** [comment]
Fixed in https://github.com/Profpatsch/yarn2nix/commit/8bc32ba6ba2e36a6d2057bdd4e18078415be704d
