### ISSUE TITLE
generate expression on the fly

### ISSUE THREAD

**Issue by ghost** [Profpatsch/yarn2nix#20]
Hi,

I am currently using moretea/yarn2nix, and was trying to figure out how I would use this.
Running yarn2nix on a lockfile does not need a network connection, right? In this case, would it be possible to build the Nix expression from the lockfile on the fly?

I am thinking about a Nix function which takes the yarn.lock file as an input and returns a derivation with the resulting node_modules.

It looks like something similar might already exist in nix-lib. Are there examples of how to use the nix-lib?

**Comment by Profpatsch** [comment]
> Running yarn2nix on a lockfile does not need a network connection, right? In this case, would it be possible to build the Nix expression from the lockfile on the fly?

It does not need a network connection, unless it contains git repositories (those need to be fetched first to calculate their hash).



> It looks like something similar might already exist in nix-lib. Are there examples of how to use the nix-lib?

The base use case is described in the README, and the functions in it are as well documented as I managed to make them.

Your exact use-case is not in the lib, but easy to achieve:

```
let
  lockfileToNpmDeps = lockfile: (pkgs.runCommandNoCC "yarn.lock" {} ''
    ${yarn2nix}/bin/yarn2nix ${lockfile} > $out
  '';
  myNpmDepsDrv = lockfileToNpmDeps ./myproject/yarn.lock
```

and then plug `myNpmDepsDrv` into the example instead of `./npm-deps.nix`.

**Comment by ghost** [comment]
If you don't mind I would leave this issue open for a moment and try to apply your snippet. Maybe I have improvements.

I think it would be nice to include a single function in nix-lib that generates the file on the fly. Including the boilerplate from the readme and from above in every module seems silly.

**Comment by Profpatsch** [comment]
Were you successful with applying the snippet?

**Comment by ghost** [comment]
I don't know anymore, but the issue is not relevant anymore for me.
