### ISSUE TITLE
Log in to private npm repository

### ISSUE THREAD

**Issue by locallycompact** [Profpatsch/yarn2nix#21]
Hi. Is there a standard way to grant `nix-build` authorization to download from a private npm registry behind a login so that yarn2nix expressions using private npm registries can be consumed?

**Comment by Profpatsch** [comment]
> Is there a standard way to grant `nix-build` authorization

No, I haven’t needed that yet. What would it entail?

**Comment by locallycompact** [comment]
I'm unsure at the moment. There's some discussion on the node2nix repo about a possible approach: https://github.com/svanderburg/node2nix/issues/151

**Comment by locallycompact** [comment]
Does `buildNodePackage` simply use `npm` under the hood? I think one solution would be to be able to have `buildNodePackage` depend on a derivation that just writes out a `~/.npmrc` file.

**Comment by Profpatsch** [comment]
> Does `buildNodePackage` simply use `npm` under the hood?

Nope, it doesn’t use `npm`.

How is a “private” package indicated?

**Comment by locallycompact** [comment]
It isn't indicated per se, just that it has a different url in `yarn.lock.nix` (e.g `http://my-custom-nexus/@mylibs/prelude`) but will result in a 401 when trying to grab the tarball from that url under `nix-build`.

**Comment by Profpatsch** [comment]
How does npm access the private repository then? How is it authorized?

**Comment by locallycompact** [comment]
In my case in particular, it is done by github auth. I don't know if this is the standard way custom nexus instances are set up.

```
curl --user <githubuser>:<githubpass> https://my-custom-nexus/repository/npm-private/@mylibs/prelude/-/prelude-1.0.0.tgz -o prelude-1.0.0.tgz
```

**Comment by locallycompact** [comment]
Is there a way to override `fetchurl` to achieve what they claim works in the `node2nix` issue?

**Comment by Profpatsch** [comment]
> In my case in particular, it is done by github auth. I don't know if this is the standard way custom nexus instances are set up.

This looks to me like standard http auth, if it works with `curl --user`.



> Is there a way to override `fetchurl` to achieve what they claim works in the `node2nix` issue?

I don’t know, please feel free to report back if you find something.

**Comment by jkopanski** [comment]
Thanks to yarn2nix using standard `fetchurl` private repos work by using this: https://github.com/NixOS/nixpkgs/issues/32732#issuecomment-352218783

**Comment by Profpatsch** [comment]
> Thanks to yarn2nix using standard `fetchurl` private repos work by using this: [NixOS/nixpkgs#32732 (comment)](https://github.com/NixOS/nixpkgs/issues/32732#issuecomment-352218783)

Awesome, do you want to add a section to the README?
